# Generated by Django 4.1 on 2022-08-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('mail', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('asunto', models.CharField(choices=[('1', 'Cotizacion'), ('2', 'Solicitud de informacion')], max_length=30)),
                ('mensaje', models.TextField(max_length=150)),
            ],
        ),
    ]
